title: "Jean-Gerard HOUNKANRIN"
logo: assets/img/profile.png
description: "Assistant Chef de Projet SI | Pilotage IT | Support Applicatif | Transformation Digitale"
theme: jekyll-theme-minimal
lang: fr
show_downloads: false
